name: Bug Report
description: Create a bug report
labels: "template: bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: If you leave out sections there is a high likelihood it will be moved to the GitHub Discussions "Help" section.
  - type: dropdown
    id: package
    attributes:
      multiple: true
      label: Which package / area of the repo does the bug impact?
      options:
        - "@vercel/remote"
        - "@vercel/remote-nx"
        - "@vercel/remote-rush"
        - other
  - type: input
    attributes:
      label: What version are you using?
      description: "For example: @vercel/remote-nx@1.0.0"
    validations:
      required: true
  - type: dropdown
    id: packageManager
    attributes:
      multiple: true
      label: What package manager are you using / does the bug impact?
      options:
        - npm
        - pnpm
        - Yarn v1
        - Yarn v2/v3
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Mac
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
  - type: markdown
    attributes:
      value: Contributors should be able to follow the steps provided in order to reproduce the bug.
  - type: markdown
    attributes:
      value: Thanks in advance!
